#916 -- Fix to logo z-index on large screen to make clickable again
undp/design-system pull request #1148
Opened 2023-03-03 21:58 UTC by paboden

#916 -- This fixes the lost logo click-ability between 1024px and 1400px (large screen) by bringing the zindex above the left and right menu blocks

2023-03-06 21:23 UTC, theadamparker approved these changes

2023-03-06 21:25 UTC, Jura requested changes
See https://github.com/undp/design-system/issues/916#issuecomment-1456490412

2023-03-08 13:13 UTC, Jura approved these changes

2023-03-09 19:51 UTC, Jura approved these changes

2023-03-09 19:52 UTC, merged