Created pagewide card
undp/design-system pull request #127
Opened 2021-10-31 15:37 UTC by pallavikadam-srijan

Created page-wide featured content card

2021-11-01 08:16 UTC, surbhi90 requested changes
Please check the comment on PR

2021-11-01 08:16 UTC, surbhi90 commented on stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/pagewidecard.scss
> +		border-top: 2px solid #000000;
@pallavikadam-srijan Please use proper variables

2021-11-01 08:16 UTC, surbhi90 commented on stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/pagewidecard.scss
> +		padding-top: 16px;
@pallavikadam-srijan Please use proper variables

2021-11-01 08:16 UTC, surbhi90 commented on stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/pagewidecard.scss
> +}
@@pallavikadam-srijan Please use proper spacing variables and mixins

2021-11-01 08:16 UTC, surbhi90 commented on stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/pagewidecard.scss
> +					transition: opacity .5s ease;
@pallavikadam-srijan please use the mixin

2021-11-01 08:35 UTC, pallavikadam-srijan commented on stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/PageWideCard.jsx
> +          <span className="wide-card__wrapper--summary">
done

2021-11-01 08:35 UTC, pallavikadam-srijan commented on stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/PageWideCard.jsx
> +            </a>
done

2021-11-01 08:36 UTC, pallavikadam-srijan commented on stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/pagewidecard.scss
> +		border-top: 2px solid #000000;
done

2021-11-01 08:36 UTC, pallavikadam-srijan commented on stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/pagewidecard.scss
> +		padding-top: 16px;
done

2021-11-02 06:10 UTC, surbhi90 requested changes
Please check the comment

2021-11-02 06:10 UTC, surbhi90 commented on stories/Organism/Blocks/FeaturedContentCard/PagewideContentCard/pagewidecard.scss
> +    border-top: 2px solid #000;
@pallavikadam-srijan Please use variables

2021-11-02 06:31 UTC, surbhi90 approved these changes

2021-11-02 09:50 UTC, surbhi90 approved these changes

2021-11-02 09:50 UTC, merged