color atom created
undp/design-system pull request #16
Opened 2021-09-20 13:46 UTC by harishkumar-srijan

color atom created

2021-09-21 07:31 UTC, surbhi90 commented on stories/Atom/Global/Color/color.stories.mdx
> +<div className="subheading">How to Use </div>
@harishkumar-srijan can we remove this section from here and add its content in the usage

2021-09-21 08:07 UTC, srijan-mehul-gada commented on stories/Atom/Global/Color/color.stories.mdx
> +# Color Component
Please use Grammarly to correct grammatical errors

2021-09-21 08:09 UTC, srijan-mehul-gada requested changes
Please review documentation again for grammatical error and also make sure it is having logical flow

2021-09-21 11:34 UTC, srijan-mehul-gada commented on stories/Atom/Global/Color/color.stories.mdx
> +Color component represent the all colors we are used into the website. we used all the colors as variables.
please use the below text:

This component represents various colors that can be used in the website as per Brand guidelines. All these colors are defined as SCSS variables globally and accordingly used in all the components. The variables can be found in assets/scss/_variables.scss file. 

Colors are divided into two options - Primary and Accents colors.

2021-09-21 11:37 UTC, srijan-mehul-gada reviewed
update documentation text as mentioned in the comment

2021-09-22 13:13 UTC, surbhi90 requested changes
Please check the comments

2021-09-22 13:13 UTC, surbhi90 commented on stories/Atom/Global/Color/color.stories.mdx
> +
@harishkumar-srijan Variables defined in scss point mentioned 2-3 times so just keep it in usage section

2021-09-22 13:13 UTC, surbhi90 commented on stories/Atom/Global/Color/color.stories.mdx
> +Primary colours are the base colours of the UI, the ones that are used most frequently in the interface. it is used for brand elements and non-interactive elements. Interactive colours are used for p
@harishkumar-srijan multiple colors spellings are used

2021-09-22 13:13 UTC, surbhi90 commented on stories/Atom/Global/Color/color.stories.mdx
> +<li>We can use by through variables that are is define in <code>assests/scss/variables.scss</code></li>
@harishkumar-srijan correct below spelling

2021-09-23 05:28 UTC, surbhi90 approved these changes
Looks good to me

2021-09-23 05:28 UTC, merged