reach elements are created
undp/design-system pull request #18
Opened 2021-09-21 12:32 UTC by harishkumar-srijan

reach elements are created

2021-09-21 13:42 UTC, surbhi90 requested changes
Please check the mentioned commentd

2021-09-21 13:42 UTC, surbhi90 commented on stories/Atom/Reach-element/Table/table.stories.mdx
> +    //return <Breadcrumb blockquote={caption.blockquote} cite={caption.cite}></Breadcrumb>;
@harishkumar-srijan remove commented code

2021-09-21 13:42 UTC, surbhi90 commented on stories/assets/scss/_breakpoints.scss
> +}
@harishkumar-srijan these should be the breakpoints
/* Mobiles only */
@media screen and (max-width: 47.9375em) {}

/* Above Mobiles */
@media screen and (min-width: 48em) {}

/* Tablets only */
@media screen and (min-width: 48em) and (max-width: 89.9375em) {}

/* Large Desktops */
@media screen and (min-width: 90em) {}

2021-09-21 13:45 UTC, srijan-mehul-gada commented on stories/Atom/Reach-element/Details/details.stories.mdx
> +
I agree with Surbhi

2021-09-22 06:54 UTC, surbhi90 reviewed
Please check comments

2021-09-22 06:54 UTC, surbhi90 commented on stories/assets/scss/_variables.scss
> +$black: #000;
@harishkumar-srijan Please update the color variables from color

2021-09-22 09:22 UTC, surbhi90 approved these changes
LGTM

2021-09-22 09:23 UTC, merged