navigation atoms
undp/design-system pull request #28
Opened 2021-09-23 09:46 UTC by harishkumar-srijan

Navigation atoms created

2021-09-23 10:40 UTC, surbhi90 requested changes
Please check the comments

2021-09-23 10:40 UTC, surbhi90 commented on stories/Atom/Navigation/Breadcrumb/Breadcrumb.jsx
> +    </ul>
@harishkumar-srijan We should not use the complete ul tag for breadcrumb item

2021-09-23 10:40 UTC, surbhi90 commented on stories/Atom/Navigation/Breadcrumb/Breadcrumb.stories.mdx
> +import { Meta, Story, ArgsTable } from '@storybook/addon-docs';
@harishkumar-srijan Remove ArgsTable

2021-09-23 10:40 UTC, surbhi90 commented on stories/Atom/Navigation/Language-switcher-row/LanguageSwitcherRow.jsx
> +};
@harishkumar-srijan Do we have red and white variants of languageswitcher

2021-09-23 10:40 UTC, surbhi90 commented on stories/Atom/Navigation/Language-switcher-row/LanguageSwitcherRow.scss
> +  max-width: 100px;
@harishkumar-srijan use min-width instead max-width

2021-09-23 10:40 UTC, surbhi90 commented on stories/Atom/Navigation/Loader/loader.scss
> +  border-top: 8px solid #f3f3f3;
@harishkumar-srijan use the variable

2021-09-23 10:40 UTC, surbhi90 commented on stories/Atom/Navigation/Loader/loader.scss
> +    border-top: 14px solid #f3f3f3;
@harishkumar-srijan use variable

2021-09-23 10:40 UTC, surbhi90 commented on stories/Atom/Navigation/Loader/loader.stories.mdx
> +  {(args, { globals: { locale } }) => {
@harishkumar-srijan remove args, globals

2021-09-23 10:40 UTC, surbhi90 commented on stories/Atom/Navigation/ProgressBarNavigation/ProgressBarNavigation.scss
> +  .progress-bar {
@harishkumar-srijan can we give this styling outside the progress-container

2021-09-23 10:40 UTC, surbhi90 commented on stories/Atom/Navigation/Sidebar-second-level/sidebarsecondlevel.scss
> +		padding: 16px 24px 16px 48px;
@harishkumar-srijan only update the padding-left here

2021-09-23 10:40 UTC, surbhi90 commented on stories/Atom/Navigation/Sidebar-with-arrow/SidebarWithArrow.scss
> +		border-top-color: #f3f3f3;
@harishkumar-srijan use variable

2021-09-23 10:40 UTC, surbhi90 commented on stories/Atom/Navigation/Sidebar-with-arrow/SidebarWithArrow.scss
> +
@harishkumar-srijan selected and selected-up have same styling so can we create placeholder

2021-09-23 10:40 UTC, surbhi90 commented on stories/Atom/Navigation/Sidebar-with-arrow/SidebarWithArrow.scss
> +			background-color: $color-blue-600!important;
@harishkumar-srijan don't use !important

2021-10-01 15:31 UTC, harishkumar-srijan commented
old PR, New PR merged and in the branch, we facing the style.scss, style.map issue in this PR

2021-10-04 07:17 UTC, surbhi90 commented
Due to conflicts, closing this PR

2021-10-04 07:17 UTC, closed without merging