Und 555
undp/design-system pull request #346
Opened 2021-12-22 17:32 UTC by Ashish-srij

UND 555 changes

2021-12-23 11:35 UTC, shishirphadke commented on stories/Organism/Text/ProjectDetail/projectdetail.scss
> +    h6 {
@Ashish-srij Close this h6 `}`. That's why the build is failing.

2021-12-29 12:23 UTC, surbhi90 commented on stories/Organism/Text/ProjectDetail/projectdetail.scss
> +h2.project-data__title {
@Ashish-srij Can we just use the h2 tag and not the class name with it

2021-12-29 12:23 UTC, surbhi90 requested changes
Please check the comment

2021-12-30 11:16 UTC, surbhi90 approved these changes

2021-12-30 11:36 UTC, closed without merging